### ISSUE TITLE
Password generator website 

### ISSUE THREAD

**Issue by thelordzeus** [dikshantrajput/Hacktoberfest-accepted-2022#114]
I would like to make a very simple and basic Strong password generator website using HTML, CSS and JavaScript.

**Comment by dikshantrajput** [comment]
Go for it. I have assigned it to you.

**Comment by thelordzeus** [comment]
Hi @dikshantrajput , I have created a PR. please check it and do let me know.

**Comment by thelordzeus** [comment]
@dikshantrajput i have completed the issue. Kindly review the PR
