### ISSUE TITLE
Add insertion sort

### ISSUE THREAD

**Issue by khushimarothi** [dikshantrajput/Hacktoberfest-accepted-2022#165]
please assign it and add hactoberfest labels

**Comment by atharva360** [comment]
please assign me this task...

**Comment by khushimarothi** [comment]
> please assign me this task...

create some other issue. this one is resolved

**Comment by Laxmikant-Dwivedi** [comment]
I will fix this please assigned this to me .

**Comment by AkanshuAich** [comment]
Please assign me the task.
