### ISSUE TITLE
delete a node from linked list

### ISSUE THREAD

**Issue by ayushjindal23** [dikshantrajput/Hacktoberfest-accepted-2022#94]

**Comment by ayushjindal23** [comment]
Can you assign it to me

**Comment by ayushjindal23** [comment]
@dikshantrajput

**Comment by dikshantrajput** [comment]
GO ahead assigned to you. Will add the labels once you raise the PR. Thanks for contributing

**Comment by ayushjindal23** [comment]
@dikshantrajput Now that I've contributed, you can add labels and merge it. Thanks

**Comment by janvichoudhary08** [comment]
hey please  assign me  this issue as a part of  hacktoberfest.
